### PR TITLE
Release 004

### LINKED ISSUE #127: Withdraw offer fails when it is called by NFT owner and not by maker
```
22/12/2022 11:07:08 PM
Info
}
22/12/2022 11:07:08 PM
Info
  "sn": "2"
22/12/2022 11:07:08 PM
Info
  "collectionId": "331660682",
22/12/2022 11:07:08 PM
Info
  "timestamp": "2022-12-21T14:01:00.180Z",
22/12/2022 11:07:08 PM
Info
  "blockNumber": "1421511",
22/12/2022 11:07:08 PM
Info
  "caller": "bXhWeVLtArWauM8UmbaVdDmXmo5uSDk6DAa2YxQ5zbt2sDcbW",
22/12/2022 11:07:08 PM
Info
⬤  debug     offer no: {
22/12/2022 11:07:08 PM
Critical
sqd:processor ReferenceError: [PROBLEM] Entity  needs to be real
    at needTo (/squid/lib/mappings/utils/consolidator.js:45:15)
    at plsBe (/squid/lib/mappings/utils/consolidator.js:35:12)
    at handleOfferWithdraw (/squid/lib/mappings/index.js:297:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HandlerRunner.processBlock (/squid/node_modules/@subsquid/substrate-processor/lib/processor/handlerProcessor.js:506:25)
    at async /squid/node_modules/@subsquid/typeorm-store/lib/database.js:157:13
    at async EntityManager.transaction (/squid/node_modules/typeorm/entity-manager/EntityManager.js:72:28)
    at async FullTypeormDatabase.runTransaction (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:155:9)
    at async FullTypeormDatabase.transact (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:64:24)
    at async HandlerRunner.processBatch (/squid/node_modules/@subsquid/substrate-processor/lib/processor/handlerProcessor.js:471:13)
22/12/2022 11:12:10 PM
Info
> node lib/processor.js
22/12/2022 11:12:10 PM
Info
> @kodadot1/snek@0.0.4 processor:start
22/12/2022 11:12:11 PM
Warning
sqd:processor .setBatchSize() is deprecated and has no effect
22/12/2022 11:12:11 PM
Info
●  note      Welcome to the Processor! ROCOCO
22/12/2022 11:12:11 PM
Info
sqd:processor last processed block was 1421177
22/12/2022 11:12:11 PM
Info
sqd:processor processing blocks from 1421178
22/12/2022 11:12:12 PM
Info
sqd:processor prometheus metrics are served at port 3000
22/12/2022 11:12:12 PM
Info
☐  pending   [WITHDRAW OFFER]: 1421511
22/12/2022 11:12:12 PM
Info
}
22/12/2022 11:12:12 PM
Info
  "sn": "2"
22/12/2022 11:12:12 PM
Info
  "collectionId": "331660682",
22/12/2022 11:12:12 PM
Info
  "timestamp": "2022-12-21T14:01:00.180Z",
22/12/2022 11:12:12 PM
Info
  "blockNumber": "1421511",
22/12/2022 11:12:12 PM
Info
  "caller": "bXhWeVLtArWauM8UmbaVdDmXmo5uSDk6DAa2YxQ5zbt2sDcbW",
22/12/2022 11:12:12 PM
Info
⬤  debug     offer no: {
22/12/2022 11:12:12 PM
Critical
sqd:processor ReferenceError: [PROBLEM] Entity  needs to be real
    at needTo (/squid/lib/mappings/utils/consolidator.js:45:15)
    at plsBe (/squid/lib/mappings/utils/consolidator.js:35:12)
    at handleOfferWithdraw (/squid/lib/mappings/index.js:297:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HandlerRunner.processBlock (/squid/node_modules/@subsquid/substrate-processor/lib/processor/handlerProcessor.js:506:25)
    at async /squid/node_modules/@subsquid/typeorm-store/lib/database.js:157:13
    at async EntityManager.transaction (/squid/node_modules/typeorm/entity-manager/EntityManager.js:72:28)
    at async FullTypeormDatabase.runTransaction (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:155:9)
    at async FullTypeormDatabase.transact (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:64:24)
    at async HandlerRunner.processBatch (/squid/node_modules/@subsquid/substrate-processor/lib/processor/handlerProcessor.js:471:13)
22/12/2022 11:17:23 PM
Info
```

### PR DESCRIPTION
**Pull request by roiLeo**
TS error:
```bash
Unsafe member access .maker on an `any` value
```

need little help to edit `MarketplaceOfferWithdrawnEvent` event

### PR type

- [x] Bugfix

### What's new?

- [x] PR closes #127 

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've run the indexer and it hasn't failed
- [ ] I've changed schema and performed a migration
- [x] I found edge cases (see #127 comments)

### Screenshot

Capture d’écran 2023-01-04 à 9 20 02 AM

### CODE REVIEW

File: src/mappings/index.ts [hunk 1]
```diff
@@ -288,9 +288,11 @@ export async function handleOfferPlace(context: Context): Promise<void> {
   // logger.debug(`offer: ${JSON.stringify({ ...event, price: String(event.amount), expiresAt: String(event.expiresAt)  }, null, 2)}`)
   const id = createTokenId(event.collectionId, event.sn);
   const entity = ensure<NE>(await get(context.store, NE, id));
-  plsBe(real, entity);
+  
+  // entity doesn't need to exist
```
Comment (vikiival) [inline src/mappings/index.ts:292]: NFT has to exist

**Review by vikiival — CHANGES_REQUESTED** [review]
Otherwise oki

File: src/mappings/index.ts (hunk 1 above)
Comment (roiLeo) [reply src/mappings/index.ts:292]: https://github.com/galacticcouncil/Basilisk-node/blob/master/pallets/marketplace/src/tests/make_offer.rs#L6

Comment (roiLeo) [reply src/mappings/index.ts:292]: & https://github.com/galacticcouncil/Basilisk-node/blob/master/pallets/marketplace/src/lib.rs#L169
no check if NFT exist

File: src/mappings/utils/getters.ts [hunk 2]
```diff
@@ -219,15 +219,16 @@ export function getPlaceOfferEvent(ctx: Context): MakeOfferEvent {
...
 }
 
-export function getWithdrawOfferEvent(ctx: Context): BaseOfferEvent {
+export function getWithdrawOfferEvent(ctx: Context): WithdrawOfferEvent {
   const event = new MarketplaceOfferWithdrawnEvent(ctx);
+
   if (event.isV55) {
     const { who: caller, class: classId, instance: instanceId } = event.asV55;
-    return { collectionId: classId.toString(), sn: instanceId.toString(), caller: addressOf(caller) };
+    return { collectionId: classId.toString(), sn: instanceId.toString(), caller: addressOf(caller), maker: addressOf(ctx.event.call?.args.maker) };
```
Comment (roiLeo) [inline src/mappings/utils/getters.ts:227]: any idea how to fix this line? or have something a bit cleaner

Comment (vikiival) [reply src/mappings/utils/getters.ts:227]: I think this is sufficient

File: src/mappings/index.ts (hunk 1 above)
Comment (vikiival) [reply src/mappings/index.ts:292]: Good catch!

But It can fail on unknown foreign key in DB 🤔

**Comment by vikiival** [comment]
Also @roiLeo I think this update should go to main imo

File: src/mappings/index.ts (hunk 1 above)
Comment (roiLeo) [reply src/mappings/index.ts:292]: > Good catch!
> 
> But It can fail on unknown foreign key in DB 🤔

which foreign key? it only concerns Offers, if you find a particular case I would like to see it

I think we have no choice here you can check  https://github.com/kodadot/snek/issues/127 to know why I've made this particular change

**Comment by roiLeo** [comment]
> Also @roiLeo I think this update should go to main imo

well depend how you want to handle release, I'm more into testing it on Rococo then release it on 005.

By the way, I wanted to ask you if it was possible to have a certain right on the 004 branch since it's testnet

**Comment by vikiival** [comment]
> By the way, I wanted to ask you if it was possible to have a certain right on the 004 branch since it's testnet

Sure!

File: src/mappings/index.ts (hunk 1 above)
Comment (vikiival) [reply src/mappings/index.ts:292]: from Offers to NFTs 
But if you try that and it does not fail I am happy to try that in rococo

**Comment by roiLeo** [comment]
LETS GO!
