### PR TITLE
fix: no emit via buy and accept offer

### LINKED ISSUE #44: Transfer event should not be emitted when the transfer was done via Buy or Accept offer
The thing is that chain does emit the `nft.InstanceTransferred` when the transfer was done via Buy or accept offer. 

the correct fix is to just check which extrinsic caused the event and if buy or accept offer then just return

Ref:
- kodadot/nft-gallery#3613
- kodadot/nft-gallery#3620

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot Indexer](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #44 
- [ ] This PR is required for kodadot/nft-gallery#<issue_number>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've run the indexer and it hasn't failed
- [ ] I've changed schema and performed a migration
- [ ] I found edge cases

### Screenshot

- [ ] My contribution is a **resolver** so I have pic from playground

### CODE REVIEW

**Comment by petersopko** [comment]
@vikiival can you check please 👀

**Comment by vikiival** [comment]
Possible fix +1

But @KngZhi can you please provide more info?

**Comment by KngZhi** [comment]
image

This is recently bought by me. The above screenshot is from this PR.

following is beta site.

Screen Shot 2022-07-31 at 8 34 23 PM

@vikiival

File: src/mappings/index.ts [hunk 1]
```diff
@@ -156,6 +158,10 @@ export async function handleTokenCreate(context: Context): Promise<void> {
 }
 
 export async function handleTokenTransfer(context: Context): Promise<void> {
+  if (context.extrinsic && [Extrinsic.acceptOffer, Extrinsic.buy].includes(context.extrinsic?.name as Extrinsic)) {
+    return;
+  }
+
```
Comment (vikiival) [inline src/mappings/index.ts:164]:
```suggestion
  if (context.extrinsic && [Extrinsic.acceptOffer, Extrinsic.buy].includes(context.extrinsic?.name as Extrinsic)) {
    logger.info(`[SEND] SKIP: ${context.event.blockNumber}, because of ${context.extrinsic?.name}`);
    return;
  }

```

**Review by vikiival — CHANGES_REQUESTED** [review]
Smol

**Comment by vikiival** [comment]
Thanks for the screenshots @KngZhi!

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
Let's merge it hope it won't break something

**Comment by KngZhi** [comment]
hi @vikiival, when could we deploy it to test?

**Comment by vikiival** [comment]
cc @KngZhi 
https://github.com/kodadot/snek/issues/44#issuecomment-1201064718

**Comment by KngZhi** [comment]
Thanks :)
